### PR TITLE
Created a mobile and small viewport interface & Improved Character Selector Screen

### PR DESCRIPTION
**Pull request by D4RKONION**
I've overhauled the character selection screen layout so that future characters added will be wrapped properly, while fixing some of the overlaying that was happening with the character pictures. This should fix [#21](https://github.com/Leimi/nautsbuilder/issues/21). However, I'd still recommend either improving the raw PNG files (I'd be happy to do it if you're willing to host them on the server) as some of them have huge amounts of transparent areas which are causing sizing issues.

I've also added almost complete mobile support, with a mobile and small viewport specific character selector and build creator. It should also improve the UX when using the main site when not on full screen. The only thing that I haven't done is make the build dragging work on mobile, as that will require more delving into the source code.

### CODE REVIEW

**Comment by r0estir0bbe** [comment]
> However, I'd still recommend either improving the raw PNG files (I'd be happy to do it if you're willing to host them on the server) as some of them have huge amounts of transparent areas which are causing sizing issues.

Which images are affected by this? If possible I'd like to retain the policy that Nautsbuilder references the images from the official wiki. My suggestion would be to rework these images then upload it to the wiki under a different name which in turn gets used in Nautsbuilder.

**Comment by D4RKONION** [comment]
> Which images are affected by this?

Quite a few of them. Examples of ridiculous amounts of transparency include [Clunk](http://hydra-media.cursecdn.com/awesomenauts.gamepedia.com/5/59/Clunk_Alpha.png) and [Gnaw](http://hydra-media.cursecdn.com/awesomenauts.gamepedia.com/6/6d/CharacterRender_Gnaw.png). It's hard to make sure all the characters look well placed when they all have various amounts of height. It'd be good to have them set at a universal size.

I'll look into reworking them.

**Comment by r0estir0bbe** [comment]
I finally took my time to review your changes. First of all: I really like what you did. Especially the mobile version is nice and helps a lot. Thanks!
However, I noticed some problems, here's what I (quickly) found out:

* There is an overflow issue when Nautsbuilder is viewed with (extreme) widescreen resolutions. The image of the Awesomenaut then does not get scaled down but instead just goes below the bottom of the view page. Compare [your version](http://i.imgur.com/N0QvP3m.png) with [master](http://i.imgur.com/Ivd69cJ.png).
* When scaling down the window to the smallest possible non-mobile resolution, the ability text box on the left side flows into the Awesomenauts icon list. Compare [your version](http://i.imgur.com/XyOdx5h.png) with [master](http://i.imgur.com/RcdMVg8.png).
* On the mobile build page, hovering over any skill row changes the height of that row. This creates some kind of wobbly effect when selecting skills and is irritating (at least for me).
* On the mobile page, `Nautsbuilder` should be written with a lowercase `b`.
* You committed changes to the `data/*` and `dist/*`. These don't really belong here but that is a problem of the repository. In a future commit, I will exclude them from the GitHub. Still it's probably a good idea to remove them from your pull request (if possible).
* ~~Your change breaks the forum version of Nautsbuilder. You can check out the forum version by simply adding `/forum` to the end URL ([example]). There are two versions, one [with](http://nautsbuilder.com/#Ted_McPain/1230001100201110300111320002/1-17-17-17-20-24-28-28-2-2-24-8-14-23-3-3-3-13-7-11-11-21-23-23/forum) and one [without](http://nautsbuilder.com/#Ted_McPain/1230001100201110300111320002/forum) build order.~~ Nevermind, this actually works correctly.

**Comment by D4RKONION** [comment]
Hi there, thanks for the review. I'll look at implementing and fixing the suggestions above, and hope that will make the pull good to go.

With regards the data/* and dist/*, I'll be honest, it wasn't my intention to change any data in there and I didn't actually change anything in there personally, it may have been an automated change. I'll look at reverting it, but as you say, it probably shouldn't be in the repo.

**Comment by D4RKONION** [comment]
> There is an overflow issue when Nautsbuilder is viewed with (extreme) widescreen resolutions. The image of the Awesomenaut then does not get scaled down but instead just goes below the bottom of the view page. Compare your version with master.

I have made a stopgap fix for this, but I wont sink too much time into it until I can edit the official wiki images as these hold the key to nice, uniformly sized characters on all viewports. I have requested access to edit these images on the wiki but I have no idea how active the maintainer is or how likely he will be to allow me to change the images. I will keep you updated either way, and will submit a proper change via a fresh PR when I get access and fix this element of the site up.



> When scaling down the window to the smallest possible non-mobile resolution, the ability text box on the left side flows into the Awesomenauts icon list. Compare your version with master.

This should be fixed. If you want an even bigger buffer, it's just a case of decreasing max-height in _characters.scss for `.current-char-left, .current-char-right`

> On the mobile build page, hovering over any skill row changes the height of that row. This creates some kind of wobbly effect when selecting skills and is irritating (at least for me).

This should now function much more satisfactorily, with overflow scrolls for the skills on mobile.

> On the mobile page, Nautsbuilder should be written with a lowercase b.

Fixed, didn't realise this was the style ye were going with!

> You committed changes to the data/* and dist/*. These don't really belong here but that is a problem of the repository. In a future commit, I will exclude them from the GitHub. Still it's probably a good idea to remove them from your pull request (if possible).

I have changed the contents of data/* and dist/* to your current repo's contents. Sorry again.

> Would it be possible to resize the Awesomenauts icons back to their original size if there is enough space (i.e. there is no line break)? On my screen with ~1920px width there is enough space to display all Awesomenauts icons in 70x70 without any line breaks.

My intention here was twofold. First off, going with 55x55 future proofs the site. Adding 5 characters, 55x55 [handles it just fine](http://i.imgur.com/WaFMY4B.jpg), whereas 70x70 starts to look [a little cramped](http://i.imgur.com/auUj7dZ.jpg), even on 1920px displays. Secondly, not everyone is on a 1080 screen, [here's an example](http://i.imgur.com/CcSbNGs.png) of the menu with a regular number of characters on a surface at 70x70 and again, [at 55x55](http://i.imgur.com/lTtpfXK.png). I genuinely think the site looks better at 55x55, but at the end of the day it's up to you I suppose.

If you have any further feedback, please let me know!

**Comment by r0estir0bbe** [comment]
I still have to check your changes, but I can quickly comment on some notes:

> I have made a stopgap fix for this, but I wont sink too much time into it until I can edit the official wiki images as these hold the key to nice, uniformly sized characters on all viewports. I have requested access to edit these images on the wiki but I have no idea how active the maintainer is or how likely he will be to allow me to change the images. I will keep you updated either way, and will submit a proper change via a fresh PR when I get access and fix this element of the site up.

Just sign up on the [wiki](http://awesomenauts.gamepedia.com/) and start editing the images. For example, some days ago I fixed the transparency of [Scoop's render image](http://awesomenauts.gamepedia.com/File:CharacterRender_Paladin.png). If you have any questions, contact [rpvarela](http://awesomenauts.gamepedia.com/User:Rpvarela), he is one of the admin, main contributors and very active.

I can help you with normalizing the sizes of the images.


> My intention here was twofold. First off, going with 55x55 future proofs the site. Adding 5 characters, 55x55 handles it just fine, whereas 70x70 starts to look a little cramped, even on 1920px displays. Secondly, not everyone is on a 16:9 screen, here's an example of the menu with a regular number of characters on a surface at 70x70 and again, at 55x55. I genuinely think the site looks better at 55x55, but at the end of the day it's up to you I suppose.

I absolutely agree that 55x55 is the way to go if there is not enough space for all characters. My point was that *if* there is enough space for all character icons in 70x70 on *one line*, then display it using 70x70. But that was just some brainstorming. With the new Awesomenaut already coming, I don't see much merit in my suggestion, because on 1920x1080 there is not enough space anymore for all 70x70 icons on one line. I'd say we just change to a smaller size permanently.

Did you try various sizes for the icons, aside from 70x70 and 55x55? Are there some alternatives that you also think look good? I guess you prefer 55x55 (provided there are alternatives) - could you maybe explain why? I'm not an UI expert so I'm interested in your opinion/thoughts.

**Comment by D4RKONION** [comment]
I'll start work on the images today so, I messed up and thought I needed to change something which was locked off.
>I absolutely agree that 55x55 is the way to go if there is not enough space for all characters. My point was that if there is enough space for all character icons in 70x70 on one line, then display it using 70x70. But that was just some brainstorming. With the new Awesomenaut already coming, I don't see much merit in my suggestion, because on 1920x1080 there is not enough space anymore for all 70x70 icons on one line. I'd say we just change to a smaller size permanently.

Did you try various sizes for the icons, aside from 70x70 and 55x55? Are there some alternatives that you also think look good? I guess you prefer 55x55 (provided there are alternatives) - could you maybe explain why? I'm not an UI expert so I'm interested in your opinion/thoughts.

I see what you mean, re: trying to fit them all on one line at their biggest. I'll try to think about a solution which will allow this.

**Comment by r0estir0bbe** [comment]
> I see what you mean, re: trying to fit them all on one line at their biggest. I'll try to think about a solution which will allow this.

I don't think that is important anymore. I just wanted to know if you tried other icon sizes and why you chose 55x55.

> This should be fixed. If you want an even bigger buffer, it's just a case of decreasing max-height in _characters.scss for `.current-char-left, .current-char-right`

This works as a quick fix. But is there a way to make this scale instead of being a fixed height? It sadly [breaks](http://i.imgur.com/3F7dkgz.png) if the icons are spread over 3 instead of 1 or 2 lines.

Additionally, I found another quick problem on your mobile viewport: The beta image is not [scaled down](http://i.imgur.com/7BZGEzZ.png) compared to the other ones.

**Comment by D4RKONION** [comment]
Hey, I've been on holidays the last week, just getting back to this now.

>This works as a quick fix. But is there a way to make this scale instead of being a fixed height? It sadly breaks if the icons are spread over 3 instead of 1 or 2 lines.

In my opinion, this is the kind of thing which can be addressed when it's an issue, I think it's a pretty extreme case for now.

>Additionally, I found another quick problem on your mobile viewport: The beta image is not scaled down compared to the other ones.

This is due to the source Ksenia image being bigger than all the others. I'll set the images to a fixed size.

I've edited all the characters so that they no longer have unneccary padding. This takes a while to propagate throughout the wiki server, so I'll begin working on fixing it on the nautsbuilder side ASAP.

**Comment by D4RKONION** [comment]
As per the commit message, all should be good to go now.

**Comment by r0estir0bbe** [comment]
I quickly checked again and so far, I was only able to figure out one very small issue: In the mobile viewport the page uses more than 100% height. I always get a scrollbar on the right side ([example](http://i.imgur.com/DTujGCC.png)).

Other than that it looks good and ready to go. Do you want me to merge now and address the small problem in a new issue or fix it before merging?

**Comment by D4RKONION** [comment]
Fixed, good catch :) If you spot anything else let me know, but I should hope that's that. Hard to catch all the fringe cases.

**Comment by r0estir0bbe** [comment]
Perfect. So far I haven't seen any other issue with your changes. There is a small regarding the footer overflowing the page if it breaks into two lines. But that's already an issue and not really that important.

Thank you!

**Pull request merged**
